#! /bin/sh
#===================#
#                   #
#  Snax's bspwmrc!  #
#                   #
#===================#

xsetroot -cursor_name left_ptr
sxhkd &
#feh --bg-scale /home/caligula/Pictures/wallpapers/file.name
compton &
#xsetroot -solid "#E2A96A"
#hsetroot -solid "#424242"
hsetroot -solid "#67605e"
wal -i "$HOME/Pictures/wal" -o wal-set
polybar rome &
termite &

### GENERAL STUFF ###
bspc monitor -d trm ffx atm vlc add

bspc config border_width         4
bspc config window_gap           16

bspc config split_ratio          0.50
bspc config top_padding          20
bspc config bottom_padding       20
bspc config left_padding         20
bspc config right_padding        20
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Atom desktop='^3' follow=on
bspc rule -a Vlc desktop='^4' follow=on
bspc rule -a feh state=floating
#bspc rule -a mplayer2 state=floating
bspc rule -a Termite state=floating
bspc rule -a Gnome-terminal state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

### MOUSE ###
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
#bspc config click_to_focus true

### COLORS ###
bspc config normal_border_color '#424242'
#bspc config focused_border_color '#FFCD98'
#bspc config focused_border_color '#2E2E2E'
bspc config focused_border_color '#555555'
bspc config active_border_color '#F7BE81'
bspc config urgent_border_color '#CC0000'
#bspc config presel_feedback_color '#67605e'
bspc config presel_feedback_color '#555555'
