#! /bin/sh
#=============================#
#     Caligula's bspwmrc.     #
#=============================#


### AUTOSTART ###
xsetroot -cursor_name left_ptr
sxhkd &
polybar antium &
redshift &
termite &

### GENERAL STUFF ###
bspc monitor -d trm web atm dis vlc

bspc config border_width         2
bspc config window_gap           21

bspc config split_ratio          0.50
bspc config top_padding          10
bspc config bottom_padding       10
bspc config left_padding         10
bspc config right_padding        10
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle  false
bspc config single_monocle       true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config ignore_ewmh_focus    true

bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a Atom desktop='^3' follow=on
bspc rule -a discord desktop='^4' follow=on #state=fullscreen
bspc rule -a Steam desktop='^4' follow=on
bspc rule -a Vlc desktop='^5' follow=on
bspc rule -a feh state=fullscreen
#bspc rule -a cool-retro-term state=floating
bspc rule -a Thunar state=floating
bspc rule -a Termite state=floating follow=on
bspc rule -a Gnome-terminal state=floating
#bspc rule -a Screenkey manage=off

### MOUSE ###
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
#bspc config click_to_focus        true
pointer_follows_monitor           false

### COLORS ###
# Set the colors from script.
source "$HOME/scripts/scheme-CanvasedPastel.sh"
#source "$HOME/scripts/scheme-xErosion.sh"
xsetroot -solid $background
#hsetroot -solid $background
bspc config normal_border_color $color0
bspc config focused_border_color $color1
bspc config active_border_color $color1
bspc config urgent_border_color $foreground
bspc config presel_feedback_color $color1
