#! /bin/sh
#=========================#
#     Snax's bspwmrc.     #
#=========================#


### AUTOSTART ###
xsetroot -cursor_name left_ptr
sxhkd &
#feh --bg-scale /home/caligula/Pictures/wallpapers/file.name
#xsetroot -solid "#E2A96A"
#hsetroot -solid "#67605e"
wal -i "$HOME/Pictures/wal"
polybar rome &
compton &
redshift &
termite &

### GENERAL STUFF ###
bspc monitor -d trm ffx atm vlc add

bspc config border_width         4
bspc config window_gap           16

bspc config split_ratio          0.50
bspc config top_padding          20
bspc config bottom_padding       20
bspc config left_padding         20
bspc config right_padding        20
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Atom desktop='^3' follow=on state=fullscreen
bspc rule -a Vlc desktop='^4' follow=on
bspc rule -a discord desktop='^5' follow=on state=fullscreen
#bspc rule -a feh state=floating
#bspc rule -a cool-retro-term state=floating
bspc rule -a Thunar state=floating
bspc rule -a Termite state=floating
bspc rule -a Gnome-terminal state=floating
#bspc rule -a Screenkey manage=off

### MOUSE ###
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
#bspc config click_to_focus true

### COLORS ###
# Set the custom colors from wal.
source "$HOME/.cache/wal/colors.sh"
bspc config normal_border_color $color0
bspc config focused_border_color $color7
bspc config active_border_color $color1
bspc config urgent_border_color $color1
bspc config presel_feedback_color $color7
#bspc config normal_border_color '#2E2E2E'
#bspc config focused_border_color '#444444'
#bspc config active_border_color '#2E2E2E'
#bspc config urgent_border_color '#CC0000'
#bspc config presel_feedback_color '#444444'
